//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace int422Final.Private.Models
{
    public partial class v_Customer
    {
        #region Primitive Properties
    
        public virtual string customer_id
        {
            get;
            set;
        }
    
        public virtual string c_password
        {
            get;
            set;
        }
    
        public virtual string l_name
        {
            get;
            set;
        }
    
        public virtual string f_name
        {
            get;
            set;
        }
    
        public virtual string licence_type
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<v_Customer_Vehicle> v_Customer_Vehicle
        {
            get
            {
                if (_v_Customer_Vehicle == null)
                {
                    var newCollection = new FixupCollection<v_Customer_Vehicle>();
                    newCollection.CollectionChanged += Fixupv_Customer_Vehicle;
                    _v_Customer_Vehicle = newCollection;
                }
                return _v_Customer_Vehicle;
            }
            set
            {
                if (!ReferenceEquals(_v_Customer_Vehicle, value))
                {
                    var previousValue = _v_Customer_Vehicle as FixupCollection<v_Customer_Vehicle>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupv_Customer_Vehicle;
                    }
                    _v_Customer_Vehicle = value;
                    var newValue = value as FixupCollection<v_Customer_Vehicle>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupv_Customer_Vehicle;
                    }
                }
            }
        }
        private ICollection<v_Customer_Vehicle> _v_Customer_Vehicle;

        #endregion

        #region Association Fixup
    
        private void Fixupv_Customer_Vehicle(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (v_Customer_Vehicle item in e.NewItems)
                {
                    item.v_Customer = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (v_Customer_Vehicle item in e.OldItems)
                {
                    if (ReferenceEquals(item.v_Customer, this))
                    {
                        item.v_Customer = null;
                    }
                }
            }
        }

        #endregion

    }
}
