//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace int422Final.Private.Models
{
    public partial class exam_Entities : ObjectContext
    {
        public const string ConnectionString = "name=exam_Entities";
        public const string ContainerName = "exam_Entities";
    
        #region Constructors
    
        public exam_Entities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public exam_Entities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public exam_Entities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<v_Customer> v_Customer
        {
            get { return _v_Customer  ?? (_v_Customer = CreateObjectSet<v_Customer>("v_Customer")); }
        }
        private ObjectSet<v_Customer> _v_Customer;
    
        public ObjectSet<v_Customer_Vehicle> v_Customer_Vehicle
        {
            get { return _v_Customer_Vehicle  ?? (_v_Customer_Vehicle = CreateObjectSet<v_Customer_Vehicle>("v_Customer_Vehicle")); }
        }
        private ObjectSet<v_Customer_Vehicle> _v_Customer_Vehicle;
    
        public ObjectSet<v_Vehicle_Model> v_Vehicle_Model
        {
            get { return _v_Vehicle_Model  ?? (_v_Vehicle_Model = CreateObjectSet<v_Vehicle_Model>("v_Vehicle_Model")); }
        }
        private ObjectSet<v_Vehicle_Model> _v_Vehicle_Model;

        #endregion
    }
}
