//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace int422Final.Private.Models
{
    public partial class v_Customer_Vehicle
    {
        #region Primitive Properties
    
        public virtual int vuId
        {
            get;
            set;
        }
    
        public virtual string model_id
        {
            get { return _model_id; }
            set
            {
                if (_model_id != value)
                {
                    if (v_Vehicle_Model != null && v_Vehicle_Model.model_id != value)
                    {
                        v_Vehicle_Model = null;
                    }
                    _model_id = value;
                }
            }
        }
        private string _model_id;
    
        public virtual string customer_id
        {
            get { return _customer_id; }
            set
            {
                if (_customer_id != value)
                {
                    if (v_Customer != null && v_Customer.customer_id != value)
                    {
                        v_Customer = null;
                    }
                    _customer_id = value;
                }
            }
        }
        private string _customer_id;
    
        public virtual bool insured
        {
            get;
            set;
        }
    
        public virtual string color
        {
            get;
            set;
        }
    
        public virtual string trans
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual v_Customer v_Customer
        {
            get { return _v_Customer; }
            set
            {
                if (!ReferenceEquals(_v_Customer, value))
                {
                    var previousValue = _v_Customer;
                    _v_Customer = value;
                    Fixupv_Customer(previousValue);
                }
            }
        }
        private v_Customer _v_Customer;
    
        public virtual v_Vehicle_Model v_Vehicle_Model
        {
            get { return _v_Vehicle_Model; }
            set
            {
                if (!ReferenceEquals(_v_Vehicle_Model, value))
                {
                    var previousValue = _v_Vehicle_Model;
                    _v_Vehicle_Model = value;
                    Fixupv_Vehicle_Model(previousValue);
                }
            }
        }
        private v_Vehicle_Model _v_Vehicle_Model;

        #endregion
        #region Association Fixup
    
        private void Fixupv_Customer(v_Customer previousValue)
        {
            if (previousValue != null && previousValue.v_Customer_Vehicle.Contains(this))
            {
                previousValue.v_Customer_Vehicle.Remove(this);
            }
    
            if (v_Customer != null)
            {
                if (!v_Customer.v_Customer_Vehicle.Contains(this))
                {
                    v_Customer.v_Customer_Vehicle.Add(this);
                }
                if (customer_id != v_Customer.customer_id)
                {
                    customer_id = v_Customer.customer_id;
                }
            }
        }
    
        private void Fixupv_Vehicle_Model(v_Vehicle_Model previousValue)
        {
            if (previousValue != null && previousValue.v_Customer_Vehicle.Contains(this))
            {
                previousValue.v_Customer_Vehicle.Remove(this);
            }
    
            if (v_Vehicle_Model != null)
            {
                if (!v_Vehicle_Model.v_Customer_Vehicle.Contains(this))
                {
                    v_Vehicle_Model.v_Customer_Vehicle.Add(this);
                }
                if (model_id != v_Vehicle_Model.model_id)
                {
                    model_id = v_Vehicle_Model.model_id;
                }
            }
        }

        #endregion
    }
}
